blank_issues_enabled: false
contact_links:
  - name: show-wifi-password discussion
    url: https://github.com/ggfevans/show-wifi-password/discussions
    about: For questions, ideas, or general discussion about the tool
